services:
  nginx:
    image: nginx:alpine
    profiles: ["production"]
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - ./nginx/conf:/etc/nginx/conf.d
      - ./nginx/ssl:/etc/nginx/ssl
      - static_volume:/var/www/static
      - media_volume:/var/www/media
    depends_on:
      - app
    restart: always
    networks:
      - app-network

  app:
    image: ghcr.io/${GITHUB_REPOSITORY}:${GITHUB_REF_NAME}
    ports: []  # Remove port exposure in production (handled by nginx)
    command: sh run.sh

  celery:
    image: ghcr.io/${GITHUB_REPOSITORY}:${GITHUB_REF_NAME}
    command: >
      sh -c "
            /py/bin/python manage.py wait_for_db &&
            celery -A app worker --loglevel=info --pool=solo"

  celery-beat:
    image: ghcr.io/${GITHUB_REPOSITORY}:${GITHUB_REF_NAME}
    command: >
      sh -c "
            /py/bin/python manage.py wait_for_db &&
            celery -A app beat --loglevel=info"
